### ISSUE TITLE
Tasklist: Work through quality cuts

### ISSUE THREAD

**Issue by dcschaper** [legend-exp/Juleana.jl#19]
### Tasks for Quality Cuts:
- [x] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/12
- [ ] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/13
- [ ] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/14
- [ ] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/15
