### ISSUE TITLE
Tasklist: Implement Oli's peak fitting routine (with Bayesian priors)

### ISSUE THREAD

**Issue by dcschaper** [legend-exp/Juleana.jl#3]
### Tasks for Peak-Fitting Routine Implementation:
Note: For now (since we are just now beginning to implement GitHub project organization) checked boxes indicate that the item has currently been completed, though we may still need to update the relevant issue or pull request with all of the details to determine if it is truly 'completed' to the extent that the corresponding issue can be closed.
- [x] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/4
- [x] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/5
- [x] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/6
- [x] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/7
- [x] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/8
- [x] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/9
- [x] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/10
- [x] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/11

**Comment by theHenks** [comment]
According to my list this is all done. Only p-values are missing and some code cleanup. Will move this to a new issue.
