### ISSUE TITLE
Tasklist: Charge Trapping Correction

### ISSUE THREAD

**Issue by dcschaper** [legend-exp/Juleana.jl#32]
### Tasks for Charge Trapping Correction:
- [x] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/16
- [x] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/17
- [x] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/18
