### ISSUE TITLE
Tasklist: Filter Implementation and Optimization

### ISSUE THREAD

**Issue by dcschaper** [legend-exp/Juleana.jl#33]
### Tasks for Filter Implementation and Optimization:
- [x] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/21
- [x] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/22
- [x] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/23
- [x] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/24
- [x] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/25
- [x] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/26
- [x] https://github.com/legend-exp/legend-julia-dsp-scripts/issues/30
